# Generated by Django 4.0.4 on 2022-05-09 09:39

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='dateCreated',
            field=models.DateField(default=datetime.datetime(2022, 5, 9, 9, 39, 25, 74723, tzinfo=utc), editable=False),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(related_name='likedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
