# Generated by Django 4.0.4 on 2022-05-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='lastModifiedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
